import { transformSync } from "@babel/core";
import { expect, test } from "vite-plus/test";

import preactProgressive from "./client.ts";

function transform(code: string): string {
  return transformSync(code, {
    plugins: [[preactProgressive, { mod: "__PP_MOD__<hash>", deps: ["__PP_DEPS__<hash>"] }]],
    filename: "test.jsx",
    parserOpts: { sourceType: "module", plugins: ["jsx"] },
  })!.code!;
}

// Strips the export statements generated by the plugin so hoisted functions
// can be evaluated as plain scripts via `new Function` (structural export
// output is asserted separately in the other tests).
function stripExports(code: string): string {
  return code.replace(/^export \{[^}]*};?\s*$/gm, "").replace(/^export default .*;?\s*$/gm, "");
}

test('leaves modules without "use client" untouched', () => {
  const code = `
    export function handler(props) { return props; }
    const local = () => {};
  `;
  const output = transform(code);
  expect(output).not.toContain("__pp_create_ref");
  expect(output).toContain("export function handler");
});

test('strips module-level "use client" and keeps named exports as-is', () => {
  const output = transform(`"use client";
    export function handler(props) { return props; }
  `);
  expect(output).toContain("export function handler(props)");
  expect(output).not.toContain('"use client"');
  // No client references are created on the client: the module *is* the
  // implementation the server's reference token names.
  expect(output).not.toContain("__pp_create_ref");
  expect(output).not.toContain("__pp_ref_");
});

test("keeps `export { ... }` specifiers as-is", () => {
  const output = transform(`"use client";
    const action = () => {};
    export { action, action as renamed };
  `);
  expect(output).toContain("const action = () => {};");
  expect(output).toContain("export { action, action as renamed };");
  expect(output).not.toContain("__pp_create_ref");
  expect(output).not.toContain('"use client"');
});

test("keeps default exports as-is", () => {
  const named = transform(`"use client";
    export default function Page() { return null; }
  `);
  expect(named).toContain("export default function Page()");

  const anon = transform(`"use client";
    export default function () { return null; }
  `);
  expect(anon).toContain("export default function ()");

  const ident = transform(`"use client";
    function Comp() { return null; }
    export default Comp;
  `);
  expect(ident).toContain("function Comp()");
  expect(ident).toContain("export default Comp;");

  for (const output of [named, anon, ident]) {
    expect(output).not.toContain("__pp_create_ref");
    expect(output).not.toContain('"use client"');
  }
});

test("keeps re-exports as-is", () => {
  const output = transform(`"use client";
    export { serverAction } from "./actions.js";
    export { default } from "./page.js";
  `);
  expect(output).toContain('export { serverAction } from "./actions.js";');
  expect(output).toContain('export { default } from "./page.js";');
  expect(output).not.toContain("__pp_create_ref");
  expect(output).not.toContain("_pp_imported_");
});

test("allows `export *` statements", () => {
  const output = transform(`"use client";
    export * from "./mod.js";
  `);
  expect(output).toContain('export * from "./mod.js";');
  expect(output).not.toContain('"use client"');
});

test('revives a demoted module-level "use client" below prepended imports', () => {
  const output = transform(`import "preact/debug";
    "use client";
    export function foo() { return 1; }
  `);
  expect(output).toContain('import "preact/debug";');
  expect(output).toContain("export function foo()");
  expect(output).not.toContain('"use client"');
  expect(output).not.toContain("__pp_create_ref");
});

test('hoists function-level "use client" and exports the hoisted function', () => {
  const code = `
    function makeHandler(x) {
      function handler(y) {
        "use client";
        return x + y;
      }
      return handler;
    }
  `;
  const output = transform(code);
  // Free variables become leading parameters, exactly as on the server.
  expect(output).toContain("function _pp_hoisted_handler(x, y)");
  // The client chunk exposes the hoisted implementation directly: no
  // `__pp_create_ref` helper and no `.bind` at the definition site.
  expect(output).toContain("export { _pp_hoisted_handler };");
  expect(output).not.toContain("__pp_create_ref");
  expect(output).not.toContain(".bind(null");
  expect(output).not.toContain('"use client"');

  // oxlint-disable-next-line typescript/no-implied-eval
  const hoisted = new Function(
    `${stripExports(output)}; return _pp_hoisted_handler;`,
  )() as (x: number, y: number) => number;
  expect(hoisted(40, 2)).toBe(42);
});

test("does not capture module-scope bindings in hoisted functions", () => {
  const code = `
    import { external } from "./data.js";
    const mod = 1;
    function outer(x) {
      function inner(y) {
        "use client";
        return external + mod + x + y;
      }
      return inner;
    }
  `;
  const output = transform(code);
  // Module-scope imports and top-level declarations stay in scope after
  // hoisting, so only the outer function scope's `x` becomes a parameter.
  expect(output).toContain("function _pp_hoisted_inner(x, y)");
  expect(output).toContain('import { external } from "./data.js";');
  expect(output).toContain("const mod = 1;");
  expect(output).toContain("export { _pp_hoisted_inner };");
});

test("binds only scope-local free variables for nested client components", () => {
  const code = `
    import { useState } from "preact/hooks";
    import { use } from "../lib/use.ts";

    export function route(c) {
      const label = "Count";
      function InlineCounter({ initialValue }) {
        "use client";
        const [count, setCount] = useState(use(initialValue));
        return (
          <>
            <button onClick={() => setCount((c) => c + 1)}>
              Count: {count}
            </button>
            <p>{label}: {count}</p>
          </>
        );
      }
      return <InlineCounter initialValue={1} />;
    }
  `;
  const output = transform(code);

  // Only the route-scoped `label` becomes a parameter. Module-scope imports
  // stay direct references, and the shadowed `c` in `setCount((c) => ...)`
  // is not captured.
  expect(output).toMatch(/function _pp_hoisted_InlineCounter\(label, \{/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(useState,/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(use,/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(c, label/);
  expect(output).toContain('import { useState } from "preact/hooks";');
  expect(output).toContain('import { use } from "../lib/use.ts";');
  expect(output).not.toContain("__pp_create_ref");
});

test('hoists function expressions containing "use client" and drops the original binding', () => {
  const code = `
    const external = 1;
    const get = function () {
      "use client";
      return external;
    };
  `;
  const output = transform(code);
  // `external` is module-scoped so it stays a direct reference.
  expect(output).toContain("function _pp_hoisted_anonymous()");
  expect(output).toContain("export { _pp_hoisted_anonymous };");
  expect(output).not.toContain("const get =");
  expect(output).not.toContain('"use client"');

  // oxlint-disable-next-line typescript/no-implied-eval
  const result = new Function(
    `${stripExports(output)}; return _pp_hoisted_anonymous();`,
  )() as number;
  expect(result).toBe(1);
});

test("keeps exported helpers reachable from hoisted functions", () => {
  const code = `
    export function helper() { return 1; }
    export const base = 10;
    const local = 5;
    export { local };
    function outer(x) {
      function inner(y) {
        "use client";
        return helper() + base + local + x + y;
      }
      return inner;
    }
  `;
  const output = transform(code);
  // Helpers stay as unexported declarations: only hoisted functions remain
  // exposed, but their implementations must survive treeshaking.
  expect(output).toContain("function helper()");
  expect(output).toContain("const base = 10;");
  expect(output).toContain("const local = 5;");
  expect(output).not.toContain("export function helper");
  expect(output).not.toContain("export { local }");
  expect(output).toContain("function _pp_hoisted_inner(x, y)");
  expect(output).toContain("export { _pp_hoisted_inner };");

  // oxlint-disable-next-line typescript/no-implied-eval
  const result = new Function(
    `${stripExports(output)}; return _pp_hoisted_inner(40, 2);`,
  )() as number;
  expect(result).toBe(58);
});

test("keeps default-exported helpers reachable from hoisted functions", () => {
  const code = `
    export default function helper() { return 1; }
    function outer() {
      function inner() {
        "use client";
        return helper();
      }
      return inner;
    }
  `;
  const output = transform(code);
  expect(output).toContain("function helper()");
  expect(output).not.toContain("export default");
  expect(output).toContain("export { _pp_hoisted_inner };");

  // oxlint-disable-next-line typescript/no-implied-eval
  const result = new Function(
    `${stripExports(output)}; return _pp_hoisted_inner();`,
  )() as number;
  expect(result).toBe(1);
});

test("drops pre-existing exports so only hoisted functions remain", () => {
  const code = `
    export function serverOnly() { return 1; }
    export default function serverDefault() { return 2; }
    function outer() {
      function inner() {
        "use client";
        return 3;
      }
      return inner;
    }
  `;
  const output = transform(code);
  expect(output).toContain("export { _pp_hoisted_inner };");
  expect(output).not.toContain("serverOnly");
  expect(output).not.toContain("serverDefault");
  expect(output).not.toContain("export default");
});

test('never emits a helper and strips every "use client" directive', () => {
  const code = `
    function a() {
      "use client";
      return 1;
    }
    function b() {
      "use client";
      return 2;
    }
  `;
  const output = transform(code);
  expect(output).not.toContain("__pp_create_ref");
  expect(output).not.toContain('"use client"');
  expect(output).toContain("export { _pp_hoisted_a };");
  expect(output).toContain("export { _pp_hoisted_b };");
});

test("treeshakes server-only imports and declarations around hoisted functions", () => {
  const code = `
    import { external } from "./data.js";
    import { notUsed } from "./unused.js";
    function unused() { return 1; }
    export function serverOnly() { return notUsed; }
    function outer() {
      function inner() {
        "use client";
        return external;
      }
      return inner;
    }
  `;
  const output = transform(code);
  expect(output).toContain('from "./data.js"');
  expect(output).not.toContain('from "./unused.js"');
  expect(output).not.toContain("function unused");
  expect(output).not.toContain("serverOnly");
  expect(output).toContain("export { _pp_hoisted_inner };");
});

test("drops side-effect statements over removed bindings but keeps side-effect imports", () => {
  const code = `
    import "./polyfill.js";
    function unused() { return 1; }
    function outer() {
      function inner() {
        "use client";
        return 2;
      }
      return inner;
    }
    console.log(unused());
  `;
  const output = transform(code);
  // Side-effect-only imports are always kept; statements referencing removed
  // bindings are pruned with them.
  expect(output).toContain('import "./polyfill.js";');
  expect(output).not.toContain("console.log(unused())");
  expect(output).toContain("export { _pp_hoisted_inner };");
});
