import { transformSync } from "@babel/core";
import { afterEach, expect, test } from "vite-plus/test";

import preactProgressive from "./server.ts";

afterEach(() => {
  delete (globalThis as Record<string, unknown>).__pp_server_modules;
});

function transform(code: string): string {
  return transformSync(code, {
    plugins: [[preactProgressive, { mod: "__PP_MOD__<hash>", deps: ["__PP_DEPS__<hash>"] }]],
    filename: "test.jsx",
    parserOpts: { sourceType: "module", plugins: ["jsx"] },
  })!.code!;
}

// Strips the export statements generated by the plugin so the code can be
// evaluated as a plain script via `new Function` (structural export output is
// asserted separately in the other tests).
function stripExports(code: string): string {
  return code.replace(/^export \{[^}]*};?\s*$/gm, "").replace(/^export default .*;?\s*$/gm, "");
}

test('leaves modules without "use client" untouched', () => {
  const code = `
    export function handler(props) { return props; }
    const local = () => {};
  `;
  const output = transform(code);
  expect(output).not.toContain("__pp_create_ref");
  expect(output).toContain("export function handler");
});

test('inserts the __pp_create_ref helper once for module-level "use client"', () => {
  const code = `"use client";
    export function foo() { return 1; }
  `;
  const output = transform(code);
  expect(output.match(/function __pp_create_ref\(/g)).toHaveLength(1);
  // Helper comes first, followed by the plain function, its ref and the export
  const helperIndex = output.indexOf("function __pp_create_ref(");
  const fnIndex = output.indexOf("function foo()");
  const refIndex = output.indexOf('const __pp_ref_foo = __pp_create_ref(foo, "foo")');
  const exportIndex = output.indexOf("export { __pp_ref_foo as foo };");
  expect(helperIndex).toBeGreaterThanOrEqual(0);
  expect(fnIndex).toBeGreaterThan(helperIndex);
  expect(refIndex).toBeGreaterThan(fnIndex);
  expect(exportIndex).toBeGreaterThan(refIndex);
});

test("rewrites `export function` declarations into refs", () => {
  const output = transform(`"use client";
    export function handler(props) { return props; }
  `);
  expect(output).toContain("function handler(props) {\n  return props;\n}");
  expect(output).toMatch(/const __pp_ref_handler = __pp_create_ref\(handler, "handler"\);/);
  expect(output).toContain("export { __pp_ref_handler as handler };");
});

test("rewrites `export { ... }` specifiers into refs", () => {
  const output = transform(`"use client";
    const action = () => {};
    export { action, action as renamed };
  `);
  expect(output).toMatch(/const __pp_ref_action = __pp_create_ref\(action, "action"\);/);
  expect(output).toContain("export { __pp_ref_action as action };");
  expect(output).toMatch(/const __pp_ref_action2? = __pp_create_ref\(action, "renamed"\);/);
  expect(output).toContain("as renamed };");
  // Original local declaration stays
  expect(output).toContain("const action = () => {};");
});

test("rewrites named default export function", () => {
  const output = transform(`"use client";
    export default function Page() { return null; }
  `);
  expect(output).toContain("function Page() {\n  return null;\n}");
  expect(output).toMatch(/const __pp_ref_default = __pp_create_ref\(Page, "default"\);/);
  expect(output).toContain("export default __pp_ref_default;");
});

test("rewrites anonymous default export function expression", () => {
  const output = transform(`"use client";
    export default function () { return null; }
  `);
  expect(output).toContain("function _pp_default() {\n  return null;\n}");
  expect(output).toContain('const __pp_ref_default = __pp_create_ref(_pp_default, "default");');
  expect(output).toContain("export default __pp_ref_default;");
});

test("rewrites default export identifier", () => {
  const output = transform(`"use client";
    function Comp() { return null; }
    export default Comp;
  `);
  expect(output).toContain("function Comp() {\n  return null;\n}");
  expect(output).toMatch(/const __pp_ref_default = __pp_create_ref\(Comp, "default"\);/);
  expect(output).toContain("export default __pp_ref_default;");
});

test("rewrites re-exports into import + ref + export", () => {
  const output = transform(`"use client";
    export { serverAction } from "./actions.js";
    export { default } from "./page.js";
  `);
  expect(output).toContain(
    'import { serverAction as _pp_imported_serverAction } from "./actions.js";',
  );
  expect(output).toContain(
    'const __pp_ref_serverAction = __pp_create_ref(_pp_imported_serverAction, "serverAction");',
  );
  expect(output).toContain('import { default as _pp_imported_default } from "./page.js";');
  expect(output).toContain(
    'const __pp_ref_default = __pp_create_ref(_pp_imported_default, "default");',
  );
});

test("throws on `export *` statements", () => {
  expect(() =>
    transform(`"use client";
      export * from "./mod.js";
    `),
  ).toThrow('"use client" modules cannot use `export *` statements');
});

type ClientRef = Record<string | symbol, unknown> & ((...args: unknown[]) => unknown);

function evalClientRef(code: string, name: string): ClientRef {
  // oxlint-disable-next-line typescript/no-implied-eval
  return new Function(`${stripExports(code)}; return ${name};`)() as ClientRef;
}

test("generated refs are callable and carry client reference metadata", () => {
  const code = transform(`"use client";
    export function handler(a) { return a + 1; }
  `);
  const ref = evalClientRef(code, "__pp_ref_handler");
  expect(ref.$type).toBe(Symbol.for("pp.client-reference"));
  expect(ref.$mod).toBe("__PP_MOD__<hash>");
  expect(ref.$name).toBe("handler");
  expect(ref.$deps).toEqual(["__PP_DEPS__<hash>"]);
  expect(ref.$bound).toEqual([]);
  expect(ref(41)).toBe(42);
});

test("`ref.bind` returns a new partially-applied client reference", () => {
  const code = transform(`"use client";
    export function handler(a, b) { return a + b; }
  `);
  const ref = evalClientRef(code, "__pp_ref_handler");
  const bound = (ref.bind as (this: ClientRef, ...args: unknown[]) => ClientRef)(1);
  expect(bound.$bound).toEqual([1]);
  expect(bound(2)).toBe(3);
  const bound2 = bound.bind(2);
  expect(bound2.$bound).toEqual([1, 2]);
  expect(bound2()).toBe(3);
});

test('hoists function-level "use client" functions and binds free variables', () => {
  const code = `
    function makeHandler(x) {
      function handler(y) {
        "use client";
        return x + y;
      }
      return handler;
    }
  `;
  const output = transform(code);
  // Hoisted to the top of the program with free vars prepended to params
  expect(output).toContain("function _pp_hoisted_handler(x, y) {\n  return x + y;\n}");
  // Ref created for the hoisted function
  expect(output).toContain(
    'const __pp_ref_handler = __pp_create_ref(_pp_hoisted_handler, "_pp_hoisted_handler");',
  );
  // Original site binds the ref over the free variable
  expect(output).toContain("const handler = __pp_ref_handler.bind(null, x);");

  // oxlint-disable-next-line typescript/no-implied-eval
  const factory = new Function(`${output}; return makeHandler;`)() as (x: number) => {
    (y: number): number;
    $bound: unknown[];
  };
  const handler = factory(40);
  expect(handler(2)).toBe(42);
  expect(handler.$bound).toEqual([40]);
});

test("binds only scope-local free variables for nested client components", () => {
  const code = `
    import { useState } from "preact/hooks";
    import { use } from "../lib/use.ts";

    export function route(c) {
      const label = "Count";
      function InlineCounter({ initialValue }) {
        "use client";
        const [count, setCount] = useState(use(initialValue));
        return (
          <>
            <button onClick={() => setCount((c) => c + 1)}>
              Count: {count}
            </button>
            <p>{label}: {count}</p>
          </>
        );
      }
      return <InlineCounter initialValue={1} />;
    }
  `;
  const output = transform(code);

  // The hoisted function still sees module-scope imports directly; only the
  // route-scoped `label` becomes a parameter that the client must receive.
  // The shadowed `c` in `setCount((c) => c + 1)` must not be captured.
  expect(output).toMatch(/function _pp_hoisted_InlineCounter\(label, \{/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(useState,/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(use,/);
  expect(output).not.toMatch(/function _pp_hoisted_InlineCounter\(c, label/);

  // The definition site re-binds the client reference over `label` only.
  expect(output).toContain("const InlineCounter = __pp_ref_InlineCounter.bind(null, label);");
  expect(output).not.toContain("__pp_ref_InlineCounter.bind(null, useState");
  expect(output).not.toContain("__pp_ref_InlineCounter.bind(null, use");
  expect(output).not.toContain("__pp_ref_InlineCounter.bind(null, c, label");
});

test('replaces function expressions containing "use client" with bound refs', () => {
  const code = `
    const external = 1;
    const get = function () {
      "use client";
      return external;
    };
  `;
  const output = transform(code);
  // `external` is declared at module scope, so it is still in scope after
  // hoisting and must not be transported as a bound argument.
  expect(output).toContain("function _pp_hoisted_anonymous() {\n  return external;\n}");
  expect(output).toContain("const get = __pp_ref_anonymous.bind(null);");

  // oxlint-disable-next-line typescript/no-implied-eval
  const result = new Function(`${output}; return get();`)() as number;
  expect(result).toBe(1);
});

test('only one helper is emitted even with multiple "use client" functions', () => {
  const code = `
    function a() {
      "use client";
      return 1;
    }
    function b() {
      "use client";
      return 2;
    }
  `;
  const output = transform(code);
  expect(output.match(/function __pp_create_ref\(/g)).toHaveLength(1);
  expect(output).not.toContain('"use client"');
});

test("module-level refs register their server implementation", () => {
  const output = transform(`"use client";
    export function handler(a) { return a + 1; }
  `);
  expect(output).toContain("__pp_server_modules");

  // oxlint-disable-next-line typescript/no-implied-eval
  new Function(`${stripExports(output)};`)();
  const registry = (globalThis as Record<string, any>).__pp_server_modules;
  expect(typeof registry["__PP_MOD__<hash>"]["handler"]).toBe("function");
  expect(registry["__PP_MOD__<hash>"]["handler"](41)).toBe(42);
});

test("scoped functions register a client reference", () => {
  const output = transform(`
    function makeHandler(x) {
      function handler(y) {
        "use client";
        return x + y;
      }
      return handler;
    }
  `);
  expect(output).toContain("__pp_server_modules");

  // oxlint-disable-next-line typescript/no-implied-eval
  new Function(`${output};`)();
  const registry = (globalThis as Record<string, any>).__pp_server_modules;
  // The registered ref derives bound copies through its own `.bind`, which
  // is how the decoder applies transmitted `$bound` values.
  const ref = registry["__PP_MOD__<hash>"]["_pp_hoisted_handler"];
  expect(ref.$type).toBe(Symbol.for("pp.client-reference"));
  expect(ref.$bound).toEqual([]);
  const bound = ref.bind(null, 40);
  expect(bound.$bound).toEqual([40]);
  expect(bound(2)).toBe(42);
});

test("modules without client directives register nothing", () => {
  const output = transform(`
    export function handler(props) { return props; }
  `);
  expect(output).not.toContain("__pp_server_modules");
});
